name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6

    - name: Install dependencies
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.54

    - name: Run tests with coverage
      run: |
        go generate ./...
        go test -v -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html
        go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt

    - name: Check coverage threshold
      run: |
        coverage=$(cat coverage.txt)
        coverageThreshold=20.0
        if (( $(echo "$coverage < $coverageThreshold" | bc -l) )); then
          echo "Test coverage ($coverage%) is below the threshold of $coverageThreshold%"
          exit 1
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: coverage.out

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-html
        path: coverage.html
